### ISSUE TITLE
GUI - Create a scene where a user can manage the library's inventory.

### ISSUE THREAD

**Issue by markusranda** [markusranda/Datamodulering-Project#13]
- [x] Design the FXML
- [ ] Make the buttons work
- [ ] Make the table functional

**Comment by Frodeluren** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/7957939/48343475-c4f74600-e672-11e8-8f67-7c794c7343f5.png)

**Comment by Frodeluren** [comment]
or this?
![image](https://user-images.githubusercontent.com/7957939/48344241-be69ce00-e674-11e8-8a00-e83820f76a83.png)

**Comment by markusranda** [comment]
Duplicato.
